version: '3.8'

services:
  traefik:
    image: traefik:2.10.4
    container_name: traefik
    command:
      - --log
      - --api
      - --providers.docker
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.address=:80
      - --entrypoints.wss.address=:6000
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --providers.file.filename=/etc/traefik/config.yml
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik=true
      - traefik.http.routers.traefik.tls=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/config/config.yml:/etc/traefik/config.yml:ro
      - ./traefik/certs:/etc/ssl/certs:ro
    ports:
      - '80:80'
      - '443:443'
    networks:
      - traefik
networks:
  traefik:
    name: traefik
    external: true
