http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true
  routers:
    traefik:
      rule: "Host(`traefik.docker.localhost`)"
      service: "api@internal"
      tls:
        domains:
          - main: "docker.localhost"
            sans:
              - "*.docker.localhost"
tls:
  certificates:
    - certFile: "/etc/ssl/certs/local-cert.pem"
      keyFile: "/etc/ssl/certs/local-key.pem"